---
title: "Untitled"
author: "Tao"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# install.packages("xlsx")
library("openxlsx")
library("readxl")
#install.packages("strucchange")
library("strucchange")
library("lubridate")
library("dplyr") # for data wrangling and pipelines
library("ggplot2") # for modifying fasstr plots
# install.packages("qqplotr")
library(qqplotr)
#The R package rnoaa is used to access NOAA NCDC climate data.
#install.packages("rnoaa")
library("rnoaa")
library("rgdal")
library("maptools")
library("utils")
# install.packages("ppcc")
library("ppcc")
# install.packages("gbm")
library("gbm")
# install.packages("caret")
library("caret")
#install.packages("pdp")
library("pdp")          # model visualization
```

```{r}
#unzip("goat_creek.zip")
getwd()
ws<- readOGR("layers/globalwatershed.shp")
extent<-raster::extent(ws)
```

```{r}
#This function returns an object with a dataframe with meta-information about all available GHCND weather stations.
#stations<-ghcnd_stations()
load("station.Rdata")
stations
#save(stations , file = "station.Rdata")
ws_stations<-stations[stations$latitude> extent@ymin &
           stations$latitude<extent@ymax&
           stations$longitude>extent@xmin&
           stations$longitude<extent@xmax &
             stations$last_year>2019,]
unique(ws_stations$id)
```
